In [1]:
import numpy as np
import pandas as pd

from ols_bootstrap.pairs import PairsBootstrap
from ols_bootstrap.residual import ResidualBootstrap
from ols_bootstrap.wild import WildBootstrap

In [2]:
df = pd.read_csv('./balance2018.csv')
df = df[df['sales_clean'] != 0]
df = df[['sales_clean', 'tanass_clean', 'tax']]
df = df.dropna(subset=['tanass_clean', 'tax'])

df_scaled = df.applymap(lambda x: np.log(x + 1))

/home/phamv/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (66) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df_sample = df_scaled.sample(n=10000, replace=False)

Y_data = pd.DataFrame(df_sample.iloc[:, 0])
X_data = pd.DataFrame(df_sample.iloc[:, 1:])

In [4]:
psb = PairsBootstrap(Y_data, X_data)
psb.fit()

In [5]:
psb.get_bootstap_params()

const  tanass_clean       tax
0   6.137007      0.171532  0.541677
1   6.131934      0.185885  0.520268
2   6.227376      0.171628  0.524505
3   6.181342      0.176539  0.521219
4   6.112035      0.178778  0.530389
5   6.202336      0.171306  0.529436
6   6.192174      0.165554  0.537799
7   6.150247      0.179795  0.527558
8   6.129065      0.172642  0.535324
9   6.045737      0.178628  0.543446
10  6.160930      0.176872  0.525142
11  6.074304      0.175941  0.541344
12  6.113317      0.169013  0.547627
13  6.225941      0.182656  0.504529
14  6.178621      0.182582  0.513677
15  6.144564      0.169446  0.536223
16  6.183255      0.174985  0.525323
17  6.103910      0.175400  0.542977
18  6.148957      0.183183  0.521321
19  6.246587      0.167316  0.520748
20  6.125764      0.167341  0.544698
21  6.147228      0.172559  0.537182
22  6.150473      0.168569  0.543028
23  6.163704      0.165673  0.545568
24  6.083878      0.178816  0.537611
25  6.123002      0.182836  0.530100
26  6.180014      0.164853  0.539925
27  6.102674      0.175133  0.538249
28  6.226710      0.168758  0.523579
29  6.080264      0.174703  0.543771
30  6.143145      0.176951  0.532341
31  6.135297      0.170581  0.538445
32  6.129282      0.170542  0.542918
33  6.082964      0.173359  0.549910
34  6.159546      0.181398  0.522479
35  6.014379      0.183044  0.545727
36  6.168977      0.172419  0.532091
37  6.195948      0.174229  0.526303
38  6.101489      0.177367  0.532463
39  6.170225      0.161761  0.541878
40  6.176089      0.165461  0.535977
41  6.112443      0.182834  0.526953
42  6.064358      0.169539  0.554349
43  6.149991      0.174683  0.538295
44  6.101085      0.178043  0.536027
45  6.146491      0.180719  0.525932
46  6.148811      0.172924  0.532343
47  6.191514      0.180213  0.518894
48  6.088338      0.174895  0.545653
49  6.125523      0.175627  0.537583

In [6]:
psb.get_bootstap_params(['tax', 'tanass_clean'])

tax  tanass_clean
0   0.541677      0.171532
1   0.520268      0.185885
2   0.524505      0.171628
3   0.521219      0.176539
4   0.530389      0.178778
5   0.529436      0.171306
6   0.537799      0.165554
7   0.527558      0.179795
8   0.535324      0.172642
9   0.543446      0.178628
10  0.525142      0.176872
11  0.541344      0.175941
12  0.547627      0.169013
13  0.504529      0.182656
14  0.513677      0.182582
15  0.536223      0.169446
16  0.525323      0.174985
17  0.542977      0.175400
18  0.521321      0.183183
19  0.520748      0.167316
20  0.544698      0.167341
21  0.537182      0.172559
22  0.543028      0.168569
23  0.545568      0.165673
24  0.537611      0.178816
25  0.530100      0.182836
26  0.539925      0.164853
27  0.538249      0.175133
28  0.523579      0.168758
29  0.543771      0.174703
30  0.532341      0.176951
31  0.538445      0.170581
32  0.542918      0.170542
33  0.549910      0.173359
34  0.522479      0.181398
35  0.545727      0.183044
36  0.532091      0.172419
37  0.526303      0.174229
38  0.532463      0.177367
39  0.541878      0.161761
40  0.535977      0.165461
41  0.526953      0.182834
42  0.554349      0.169539
43  0.538295      0.174683
44  0.536027      0.178043
45  0.525932      0.180719
46  0.532343      0.172924
47  0.518894      0.180213
48  0.545653      0.174895
49  0.537583      0.175627

In [7]:
psb.get_pct_ci()

params     0.025     0.975
0         const  6.049927  6.227226
1  tanass_clean  0.164990  0.183152
2           tax  0.514851  0.549396

In [8]:
psb.get_pct_ci(['tax', 'const'])

params     0.025     0.975
0    tax  0.514851  0.549396
1  const  6.049927  6.227226

In [9]:
rsb = ResidualBootstrap(Y_data, X_data)
rsb.fit()

In [10]:
rsb.orig_params

array([6.13553934, 0.17460432, 0.53482718])

In [11]:
rsb.bs_params_mean

array([6.13428907, 0.17468474, 0.53465541])

In [12]:
wb_stdn = WildBootstrap(Y_data, X_data, from_distro = 'standard_normal')
wb_stdn.fit()

In [13]:
wb_stdn.indep_varname

['const', 'tanass_clean', 'tax']

In [14]:
wb_rad = WildBootstrap(Y_data, X_data, from_distro = 'rademacher')
wb_rad.fit()

In [15]:
wb_rad.orig_params_se

array([0.03491423, 0.00387686, 0.00648328])

In [16]:
wb_rad.bs_params_se

array([0.03449165, 0.00312835, 0.0071345 ])

In [17]:
wb_mam = WildBootstrap(Y_data, X_data, from_distro = 'mammen')
wb_mam.fit()

In [18]:
psb.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                       Pairs Bootstrap results with sample size of 10000 and bootstrap resampling size of 50 using 95.00% CI                                        |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.1355    |             6.1416            |  0.0060  |      0.

In [19]:
rsb.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Residual Bootstrap results with sample size of 10000 and bootstrap resampling size of 50 using 95.00% CI                                      |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.1355    |             6.1343            |  0.0013  |      0.

In [20]:
wb_stdn.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                             Wild Bootstrap with Standard Normal results with sample size of 10000 and bootstrap resampling size of 50 using 95.00% CI                              |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.1355    |             6.1312            |  0.0043  |      0.

In [21]:
wb_rad.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                Wild Bootstrap with Rademacher results with sample size of 10000 and bootstrap resampling size of 50 using 95.00% CI                                |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.1355    |             6.1407            |  0.0052  |      0.

In [22]:
wb_mam.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                  Wild Bootstrap with Mammen results with sample size of 10000 and bootstrap resampling size of 50 using 95.00% CI                                  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.1355    |             6.1263            |  0.0092  |      0.