In [1]:
import numpy as np
import pandas as pd

from ols_bootstrap.pairs import PairsBootstrap
from ols_bootstrap.residual import ResidualBootstrap
from ols_bootstrap.wild import WildBootstrap

In [2]:
df = pd.read_csv('./balance2018.csv')
df = df[df['sales_clean'] != 0]
df = df[['sales_clean', 'tanass_clean', 'tax']]
df = df.dropna(subset=['tanass_clean', 'tax'])

df_scaled = df.applymap(lambda x: np.log(x + 1))

/home/phamv/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (66) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df_sample = df_scaled.sample(n=10000, replace=False)

Y_data = pd.DataFrame(df_sample.iloc[:, 0])
X_data = pd.DataFrame(df_sample.iloc[:, 1:])

In [4]:
psb = PairsBootstrap(Y_data, X_data, iter = 1000)
psb.fit()

In [5]:
psb.get_bootstap_params()

const  tanass_clean       tax
0    6.212569      0.183145  0.510299
1    6.260303      0.171672  0.518026
2    6.290498      0.172058  0.507845
3    6.258767      0.177509  0.505830
4    6.192625      0.179320  0.516809
..        ...           ...       ...
995  6.274089      0.171506  0.510954
996  6.237162      0.173298  0.514632
997  6.293593      0.171705  0.508194
998  6.220326      0.174053  0.522362
999  6.308433      0.176215  0.497663

[1000 rows x 3 columns]

In [6]:
psb.get_bootstap_params(['tax', 'tanass_clean'])

tax  tanass_clean
0    0.510299      0.183145
1    0.518026      0.171672
2    0.507845      0.172058
3    0.505830      0.177509
4    0.516809      0.179320
..        ...           ...
995  0.510954      0.171506
996  0.514632      0.173298
997  0.508194      0.171705
998  0.522362      0.174053
999  0.497663      0.176215

[1000 rows x 2 columns]

In [7]:
psb.get_pct_ci()

params     0.025     0.975
0         const  6.144603  6.319696
1  tanass_clean  0.160325  0.180458
2           tax  0.503581  0.539068

In [8]:
psb.get_pct_ci(['tax', 'const'])

params     0.025     0.975
0    tax  0.503581  0.539068
1  const  6.144603  6.319696

In [9]:
rsb = ResidualBootstrap(Y_data, X_data, iter = 1000)
rsb.fit()

In [21]:
rsb.orig_params

array([6.23013459, 0.17056846, 0.52159765])

In [20]:
rsb.bs_params_mean

array([6.2303283 , 0.17055853, 0.52143445])

In [10]:
wb_stdn = WildBootstrap(Y_data, X_data, iter = 1000, from_distro = 'standard_normal')
wb_stdn.fit()

In [22]:
wb_stdn.indep_varname

['const', 'tanass_clean', 'tax']

In [11]:
wb_rad = WildBootstrap(Y_data, X_data, iter = 1000, from_distro = 'rademacher')
wb_rad.fit()

In [24]:
wb_rad.orig_params_se

array([0.03542144, 0.0038802 , 0.00658306])

In [25]:
wb_rad.bs_params_se

array([0.03448586, 0.00373235, 0.00643937])

In [12]:
wb_mam = WildBootstrap(Y_data, X_data, iter = 1000, from_distro = 'mammen')
wb_mam.fit()

In [13]:
psb.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Pairs Bootstrap results with sample size of 10000 and bootstrap resampling size of 1000 using 95.00% CI                                       |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.2301    |             6.2307            |  0.0006  |      0.

In [14]:
rsb.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                     Residual Bootstrap results with sample size of 10000 and bootstrap resampling size of 1000 using 95.00% CI                                     |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.2301    |             6.2303            |  0.0002  |      0.

In [15]:
wb_stdn.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                            Wild Bootstrap with Standard Normal results with sample size of 10000 and bootstrap resampling size of 1000 using 95.00% CI                             |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.2301    |             6.2293            |  0.0008  |      0.

In [16]:
wb_rad.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                               Wild Bootstrap with Rademacher results with sample size of 10000 and bootstrap resampling size of 1000 using 95.00% CI                               |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.2301    |             6.2289            |  0.0013  |      0.

In [17]:
wb_mam.summary()

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                 Wild Bootstrap with Mammen results with sample size of 10000 and bootstrap resampling size of 1000 using 95.00% CI                                 |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     Params     |  Orig Coeffs  |  Mean of Bootstrapped Coeffs  |   Bias   |  Orig Coeff SE  |  SE of Bootstrapped Coeffs  |  % of Diff in SE  |       PCT CI       |  PCT CI Diff  |
+----------------+---------------+-------------------------------+----------+-----------------+-----------------------------+-------------------+--------------------+---------------+
|     const      |     6.2301    |             6.2293            |  0.0008  |      0.